# Generated by Django 5.1.1 on 2024-10-22 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_publicacion', models.CharField(help_text='Título de la publicación.', max_length=50, verbose_name='Título')),
                ('publicacion', models.TextField(help_text='Texto de la publicación.', verbose_name='Texto')),
                ('resumen', models.TextField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, default='img_default/public_default.jpg', null=True, upload_to='publicaciones', verbose_name='Imagen')),
                ('fecha_publicacion', models.DateTimeField(auto_now=True, verbose_name='Publicado')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modificado')),
                ('categoria', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicacion.categoria', verbose_name='Categoría')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ('titulo_publicacion',),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_autor_publicacion', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicacion', to='publicacion.publicacion')),
            ],
        ),
    ]
