# Generated by Django 5.1.1 on 2024-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNac', models.DateField(help_text='Formato de Fecha <em>DD-MM-YYYY</em>.')),
                ('foto', models.ImageField(blank=True, default='static/usuario.png', null=True, upload_to='media')),
            ],
        ),
    ]
