# Generated by Django 5.1.1 on 2024-10-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='static/usuario.png', null=True, upload_to='media', verbose_name='Foto de Perfil'),
        ),
    ]
