# Generated by Django 5.1.1 on 2024-10-22 06:42

import apps.comentario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=apps.comentario.models.default_datatime),
        ),
    ]
